// Pet Data
let petData = [
	{
		name: 'Einstein',
		breeds: ['British Shorthair'],
		age: 'adult',
		size: 'M',
		gender: 'Male',
		details: ['Other cats ok', 'No dogs'],
		photo: 'images/Einstein.jpg',
	},
	{
		name: 'Lucy',
		breeds: ['Scottish Fold', 'British Shorthair'],
		age: 'adult',
		size: 'M',
		gender: 'Female',
		details: ['Other cats ok', 'No dogs'],
		photo: 'images/Lucy.jpg',
	},
	{
		name: 'Bella',
		breeds: ['Persian'],
		age: 'adult',
		size: 'M',
		gender: 'Female',
		details: ['No cats', 'No dogs'],
		photo: 'images/Bella.jpg',
	},
	{
		name: 'Leo',
		breeds: ['Domestic short-hair'],
		age: 'adult',
		size: 'M',
		gender: 'Male',
		details: ['Other cats ok', 'Dogs ok'],
		photo: 'images/Leo.jpg',
	},
	{
		name: 'Destiny',
		breeds: ['Maincoon'],
		age: 'adult',
		size: 'L',
		gender: 'Female',
		details: ['Other cats ok', 'No dogs'],
		photo: 'images/Destiny.jpg',
	},
	{
		name: 'Max',
		breeds: ['Maincoon'],
		age: 'adult',
		size: 'L',
		gender: 'Male',
		details: ['No cats', 'No dogs'],
		photo: 'images/Max.jpg',
	},
	{
		name: 'Milo',
		breeds: ['Domestic short-hair'],
		age: 'adult',
		size: 'M',
		gender: 'Male',
		details: ['Other cats ok', 'Dogs ok'],
		photo: 'images/Milo.jpg',
	},
	{
		name: 'Pumpkin',
		breeds: ['Domestic long-hair'],
		age: 'adult',
		size: 'L',
		gender: 'Male',
		details: ['Other cats ok', 'No dogs'],
		photo: 'images/Pumpkin.jpg',
	},
	{
		name: 'Shadow',
		breeds: ['Scottish Fold'],
		age: 'adult',
		size: 'M',
		gender: 'Male',
		details: ['No cats', 'No dogs'],
		photo: 'images/Shadow.jpg',
	},
	{
		name: 'Simba',
		breeds: ['Scottish Fold'],
		age: 'young',
		size: 'S',
		gender: 'Male',
		details: ['No cats', 'No dogs'],
		photo: 'images/Simba.jpg',
	},
]